# Run 'skaffold dev'
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: azsdkdemo
build:
  artifacts:
  - image: kaolsze3acr.azurecr.io/azsdkdemonetwebapp
    context: ../../src/net
    docker:
      dockerfile: WebApp/Dockerfile
  - image: kaolsze3acr.azurecr.io/azsdkdemonetapi
    context: ../../src/net
    docker:
      dockerfile: Api/Dockerfile
  - image: kaolsze3acr.azurecr.io/azsdkdemonetqueueservice
    context: ../../src/net
    docker:
      dockerfile: Services/QueueService/Dockerfile
deploy:
  kubectl:
    manifests:
    - ../k8s/net/*.yaml