kind: ConfigMap
metadata:
  name: websettings
apiVersion: v1
data:
  appsettings.json: |-
    {
        "API_ENDPOINT": "51.141.164.69",
        "FUNCTIONS_ENDPOINT": "http://kaolsze3function.azurewebsites.net"
    }
