# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.7"

services:
  azsdkdemonetwebapp:
    image: ${AZURE_CONTAINER_REGISTRY_SERVER}/azsdkdemonetwebapp:${CONTAINER_TAG}
    build:
      context: ../../../../src/net
      dockerfile: WebApp/Dockerfile
    depends_on:
      - azsdkdemonetapi
  azsdkdemonetapi:
    image: ${AZURE_CONTAINER_REGISTRY_SERVER}/azsdkdemonetapi:${CONTAINER_TAG}
    build:
      context: ../../../../src/net
      dockerfile: Api/Dockerfile.prod
  azsdkdemonetqueueservice:
    image: ${AZURE_CONTAINER_REGISTRY_SERVER}/azsdkdemonetqueueservice:${CONTAINER_TAG}
    build:
      context: ../../../../src/net
      dockerfile: Services/QueueService/Dockerfile.prod